rolgame/rolgame/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from apps.usuario.views import Home, Login, logoutUsuario


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home.as_view(),name='index'),
    path('usuarios/login/',Login.as_view(), name='login'),
    path('logout/',login_required(logoutUsuario), name='logout'),
    path('razas/', include(('apps.raza.urls','razas'))),
    path('equipamientos/', include(('apps.equipamiento.urls','equipamientos'))),
    path('ataques/', include(('apps.ataque.urls','ataques'))),
    path('personajes/', include(('apps.personaje.urls','personajes'))),
    path('usuarios/',include(('apps.usuario.urls','usuarios'))),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{
        'document_root': settings.MEDIA_ROOT,
    }
)
]

rolgame/apps/ataque/models.py
from django.db import models


from apps.raza.models import Raza
from apps.usuario.models import Usuario

# Create your models here.

class AtaqueEspecial(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField('Nombre del poder o habilidad',max_length=50, blank=False, null=False, unique=True)
    descripcion = models.TextField('Detalle del poder o habilidad',max_length=200,blank=False,null=False)
    imagen = models.ImageField('Imagen poder', upload_to='Poderes/', height_field = None, width_field=None,null=True,blank=True, max_length=200 )
    daño_fisico = models.IntegerField('Daño fisico', default=10)
    daño_magico = models.IntegerField('Daño magio', default=10)     
    raza = models.ForeignKey(Raza, on_delete= models.PROTECT)
    categoria_choice =(
        (1,'HABILIDAD'),
        (2,'PODER'),
    )
    categoria = models.PositiveIntegerField('Categoria del ataque especial', choices=categoria_choice,blank=False,null=False)
    creador = models.ForeignKey(Usuario, on_delete=models.CASCADE, null= True, blank=True)
    estado = models.BooleanField('Inventario en uso', default=False)
    
    class Meta:
        verbose_name= 'Ataque especial'
        verbose_name_plural = 'Ataques especiales' 
        ordering = ['nombre']

    def __str__(self) :
        return f'{self.nombre}'

    def devolver(self):
        return dict(AtaqueEspecial.categoria_choice)[self.categoria]

rolgame/templates/equipamiento/inventario/inventario_ataque/opciones/ataque_confirm_delete.html
{% extends 'home.html' %}

{% block header %}
    
{% endblock header %}
    
{% block contenido %}
    
<div class="d-flex justify-content-center  bg-dark text-light" style="width: 100%; height: 100vh">
    <div class="align-self-center text-center">

        <form method="post" class="text-light">
            {% csrf_token %}
            <p class="alert alert-warning"><strong>¿Desea eliminar el registro {{ object }}?</strong></p>
            <button type="submit" class="btn btn-danger mb-3">Confirmar</button>
        </form>
        <a href="{% url 'equipamientos:listar_inventario_especial' %}">Volver al listado </a>
        
    </div>

</div>
{% endblock contenido %}
    

{% block footer %}
    
{% endblock footer %}
    

rolgame/templates/equipamiento/inventario/inventario_ataque/opciones/crear_inventario.html
{% extends 'home.html' %}
{% load static %}

{% block header %}
        {% include 'components/header.html' %}
{% endblock  %}
    
    
    {% block contenido %}
<div class="container card">
    <div class="card-header text-center">
        <strong >Añadir habilidad o poder al inventario</strong>

    </div>
        
    <div class="card-body card-block">

        <form class="form-horizontal"  method="post" enctype="multipart/form-data" >
            {% csrf_token %}


            <div class="row mb-3 form-group">
                <div class="col col-md-3" >{{ form.personaje.label }}</div>
                <div class="col-12 col-md-9">{{form.personaje}}</div>
            </div>

            <div class="row mb-3 form-group">
                <div class="col col-md-3" >{{ form.ataque.label }}</div>
                <div class="col-12 col-md-9">{{form.ataque}}</div>
            </div>



            <div class="text-center">
                <button type="reset" class="btn btn-danger">Cancelar</button>
                <button type="submit" class="btn btn-primary">Crear</button>

            </div>

            <a href="{% url 'equipamientos:inventario' %}">Volver</a>
        </form>
    </div>
</div>
        
    {% endblock contenido %}
            
    
    {% block footer %}
        
    {% endblock footer %}
        

rolgame/templates/equipamiento/inventario/inventario_ataque/opciones/listar_inventario.html
{% extends 'home.html' %}
{% block contenido %}
<div  class="container" >
    {% if object_list %}    
    <div class="card">
        <div class="card-header text-center">
            <strong class="card-title text-uppercase">Kit de ataque </strong>
        </div>
        <div class=" table-stats order-table ov-h">
            <table class="table table-responsive">
                <thead>
                    <tr class="text-center">
                        <th>ID</th>
                        <th>NOMBRE DEL PERSONAJE</th>
                        <th>NOMBRE DEL ATAQUE</th>
                        <th>CATEGORIA</th>
                        {% if request.user.is_staff %}
                        {% else %}
                        <th>OPCIONES</th>

                        {% endif %}
                            


                    </tr>
                </thead>
                <tbody>
                    {% for inventario in object_list %}
                        <tr class="text-center">
                            <td> {{ inventario.id }} </td>
                            <td> {{ inventario.personaje.nombrePersonaje }} </td>
                            <td> {{ inventario.ataque}}</td>

                            <th>{{ inventario.ataque.get_categoria_display }}</th>
                            
                            {% if request.user.is_staff %}
                            <td>                                
                                
                            </td>
                            {% else %}
                            <td>
                                <a class="btn btn-danger" href="{% url 'equipamientos:borrar_inventario_especial' inventario.id %}">Eliminar</a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}    
                </tbody>
            </table>

            {% block paginacion %}
                {% include 'components/paginacion.html' %}
            {% endblock paginacion %}
        </div>
        <a class="p-2" href="{% url 'equipamientos:inventario' %}">Volver</a>

    </div>
{% else %}
<h1><strong><b>No existen objetos registrados en el inventario</b></strong></h1>
{% endif %}
</div>  
{% endblock contenido %}
    